import Head from 'next/head';
import { Footer } from '../components/Footer';
import { Header } from '../components/Header';
import { Post } from '../components/Post';

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-900">
        <div className="container lg:px-56 px-4">
          <Header blogName={'Blog NextJS'} />
          <Post />
          <Footer />
        </div>
      </main>
    </>
  );
}
